import numpy as np

epsilon_0 = 8.8541878128e-12

K_e = 1.0 / (4.0 * np.pi * epsilon_0)

def electric_field_point_charge(observation_point: np.ndarray, charge_position: np.ndarray, charge: float) -> np.ndarray:
    """
    Calculate the electric field generated by a point charge.

    Parameters
    ----------
    observation_point: np.ndarray
        Position at which the electric field is evaluated [m].
    charge_position: np.ndarray
        Position of the source charge [m].
    charge: float
        Source charge [C].

    Returns
    -------
    np.ndarray
        Electric-field vector [N/C].
    """

    displacement = observation_point - charge_position
    distance = np.linalg.norm(displacement)

    if np.isclose(distance, 0.0):
        raise ValueError(
            "The electric field is undefined at the charge position.")

    electric_field = K_e * charge * displacement* distance **-3

    return electric_field


def electric_field_multiple_charges(observation_point: np.ndarray, charge_positions: np.ndarray, charges: np.ndarray) -> np.ndarray:
    """
    Calculate the net electric field generated by multiple point charges.
    When entering the charge_position and charges, please enter the information accordingly.
    """
    Field = np.zeros_like(observation_point, dtype = float)
    net_charge = zip(charge_positions, charges)

    for position, charge in net_charge:
        Field += electric_field_point_charge(observation_point, position, charge)

    return Field